name: jm_workflow2

on:
  workflow_dispatch:
jobs:
  job-email:
    name: mail
    runs-on: ubuntu-latest
    steps:
      - name: mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Exercici github workflow enviament email
          # Literal body:
          body: Bon dia, sóc l'Ivan. T'envio el correu desde ${{github.repository}}. Salut!
          to: imartinez@imim.es
          from: Ivan Martinez Campos 
          # Optional content type (defaults to text/plain):
          content_type: text/html
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true

name: jm_workflow1

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'text a mostrar'
        required: true
        default: 'hello world'
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: |
          echo "${{github.event.inputs.message}}"
      - name: paso 2
        run: |
          echo estás avisado: "${{github.event.inputs.message}}"