name: jm_workflow1

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'text a mostrar'
        required: true
        default: 'hello world'
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: |
          echo "${{github.event.inputs.message}}"
      - name: paso 2
        run: |
          echo estás avisado: "${{github.event.inputs.message}}"